version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 8
    allow:
      - dependency-type: "all"
    reviewers:
      - "Cian-H"
    assignees:
      - "Cian-H"
    commit-message:
      prefix: "uv-deps"
      prefix-development: "uv-deps-dev"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
